name: Sync Gaussian Splatting (Manual)

on:
  workflow_dispatch:    # ✅ 只支持手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4

      - name: Clear existing 3dgaussian directory (optional)
        run: rm -rf 3dgaussian/*

      - name: Clone source repository
        run: |
          git clone --depth 1 https://github.com/graphdeco-inria/gaussian-splatting temp-source
          mkdir -p 3dgaussian
          cp -r temp-source/* 3dgaussian/
          rm -rf temp-source

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add 3dgaussian
          git commit -m "Manually synced gaussian-splatting to 3dgaussian/" || echo "No changes to commit"
          git push
